dist: trusty
language: c

branches:
  except:
    - gh-pages

addons:
  apt_packages:
    - libgmp-dev
    - libreadline-dev
    - libgmp-dev:i386
    - libreadline-dev:i386
    - gcc-multilib
    - g++-multilib
    - texinfo


install:
  - git clone -b master --depth=2 https://github.com/gap-system/gap.git gap-src
  - pwd
  - ( cd gap-src && ./autogen.sh || echo no autogen )
  - ( cd gap-src && ./configure && make && make bootstrap-pkg-minimal V=1)
  - pwd
  - echo ln -s $(pwd) gap-src/pkg/curlInterface
  - ln -s $(pwd) gap-src/pkg/curlInterface
  - ( cd gap-src/pkg/curlInterface && ./autogen.sh && ./configure $CONF_FLAG && make V=1)
  - pwd

script:
  - (cd gap-src && ./gap pkg/curlInterface/tst/testall.g)
