language: c

branches:
  except:
    - gh-pages

addons:
  apt_packages:
    - libgmp-dev
    - libreadline-dev
    - zlib1g-dev

matrix:
  include:
    - env: GAPBRANCH="stable-4.9"
    - env: CFLAGS="-O2" CC=clang CXX=clang++
      compiler: clang
    - env: CFLAGS="-O2"
      compiler: gcc
    - env: CFLAGS="-O2" GAP_CONFIGFLAGS="--enable-checking"
      compiler: gcc
    - env: ABI=32
      addons:
        apt_packages:
          - libcurl4-openssl-dev:i386
          - libgmp-dev:i386
          - libreadline-dev:i386
          - gcc-multilib
          - g++-multilib

before_script:
  - git clone https://github.com/gap-system/pkg-ci-scripts.git scripts
  - scripts/build_gap.sh
script:
  - scripts/build_pkg.sh && scripts/run_tests.sh
after_script:
  - scripts/gather-coverage.sh
  - bash <(curl -s https://codecov.io/bash)
